{
 "title": "Akka service overview",
 "tags": [ "kalix-managed" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kalix_region",
    "label": "Region",
    "query": "label_values(kalix_service_revision, kalix_region)"
   },
   {
    "name": "kalix_service",
    "label": "Service",
    "query": "label_values(kalix_service_revision{kalix_region=~\"$kalix_region\"}, kalix_service)"
   },
   {
    "name": "grpc_service",
    "label": "Component",
    "query": "label_values({__name__=~\"kalix_proxy_http_requests_total|kalix_proxy_grpc_requests_total\", kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"},grpc_service)"
   },
   {
    "name": "http_target",
    "label": "HTTP Target",
    "query": "label_values(kalix_proxy_http_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", grpc_service=~\"$grpc_service\"},http_target)"
   },
   {
    "name": "grpc_method",
    "label": "GRPC Method",
    "query": "label_values(kalix_proxy_grpc_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", grpc_service=~\"$grpc_service\"},grpc_method)"
   },
   {
    "name": "agent",
    "label": "Agent",
    "query": "label_values(kalix_agent_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"},agent_id)"
   },
   {
    "name": "event_sourced_entity",
    "label": "Event Sourced Entity",
    "query": "label_values(kalix_eventsourced_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"},entity_name)"
   },
   {
    "name": "key_value_entity",
    "label": "Key Value Entity",
    "query": "label_values(kalix_valueentity_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"},entity_name)"
   },
   {
    "name": "view",
    "label": "View",
    "query": "label_values(kalix_view_upsert_rows_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"},view_name)"
   },
   {
    "name": "workflow_entity",
    "label": "Workflow Entity",
    "query": "label_values(kalix_workflowentity_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}, entity_name)"
   },
   {
    "name": "projection",
    "label": "Consumers",
    "query": "label_values(kalix_projection_consumer_lag_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_type!=\"replicated_event_sourced_projection\"},projection_name)"
   },
   {
    "name": "replication_projection",
    "label": "Replication Projection",
    "query": "label_values(kalix_projection_consumer_lag_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_type=\"replicated_event_sourced_projection\"},projection_name)"
   }
  ]
 },
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 1 } },
  {
   "title": "successful requests",
   "type": "timeseries",
   "description": "Rate of successful requests per second (reqs/s) over time, by endpoint.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate({__name__=~\"kalix_proxy_grpc_requests_total\", kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", grpc_method=~\"$grpc_method\", grpc_status_code=\"0\"}[$__rate_interval])) by (kalix_region, kalix_service, grpc_method) OR sum(irate({__name__=~\"kalix_proxy_http_requests_total\", kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", http_target=~\"$http_target\", http_status_code=~\"(2|3)..\"}[$__rate_interval])) by (kalix_region, kalix_service, http_target)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{grpc_method}}{{http_target}}"
    }
   ]
  },
  {
   "title": "failed requests",
   "type": "timeseries",
   "description": "Rate of requests (reqs/s) that raised an error when processing the request, over time, by endpoint.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate({__name__=~\"kalix_proxy_grpc_requests_total\", kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", grpc_method=~\"$grpc_method\", grpc_status_code=~\"1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16\"}[$__rate_interval])) by (kalix_region, kalix_service, grpc_method) OR sum(irate({__name__=~\"kalix_proxy_http_requests_total\", kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", http_target=~\"$http_target\", http_status_code=~\"(4|5)..\"}[$__rate_interval])) by (kalix_region, kalix_service, http_target)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{grpc_method}}{{http_target}}"
    }
   ]
  },
  {
   "title": "processing time distribution (seconds) - endpoint: ${kalix_service}",
   "type": "bargauge",
   "description": "Number of requests grouped by processing duration and endpoint.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(kalix_proxy_grpc_request_duration_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", grpc_method=~\"$grpc_method\"}[$__range])) by (le) OR sum(increase(kalix_proxy_http_request_duration_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", http_target=~\"$http_target\"}[$__range])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "processing time 99p - endpoint: ${kalix_service}",
   "type": "timeseries",
   "description": "Endpoint processing time 99th percentile",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_proxy_grpc_request_duration_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", grpc_service=~\"$grpc_service\", grpc_method=~\"$grpc_method\"}[$__rate_interval])) by (kalix_region, kalix_service, grpc_method, le)) OR histogram_quantile(0.99, sum(irate(kalix_proxy_http_request_duration_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", grpc_service=~\"$grpc_service\", http_target=~\"$http_target\"}[$__rate_interval])) by (kalix_region, kalix_service, http_target, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{grpc_method}}{{http_target}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_proxy_grpc_request_duration_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", grpc_service=~\"$grpc_service\", grpc_method=~\"$grpc_method\"}[$__rate_interval])) by (kalix_region, kalix_service, grpc_method, le)) OR histogram_quantile(0.99, sum(irate(kalix_proxy_http_request_duration_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", grpc_service=~\"$grpc_service\", http_target=~\"$http_target\"}[$__rate_interval])) by (kalix_region, kalix_service, http_target, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{grpc_method}}{{http_target}}"
    }
   ]
  },
  {
   "title": "processing time heapmap",
   "type": "heatmap",
   "description": "Number of calls that fall into each processing time bucket over time.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_proxy_grpc_request_duration_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\",grpc_method=~\"$grpc_method\"}[$__rate_interval])) by (le) OR sum(irate(kalix_proxy_http_request_duration_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\",http_target=~\"$http_target\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "instances",
   "type": "timeseries",
   "description": "Number of running instances of the service.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count(kalix_service_revision{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}) by (kalix_region, kalix_service)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}}"
    }
   ]
  },
  {
   "title": "version",
   "type": "timeseries",
   "description": "A single number, always increasing, showing of the service the number of different versions deployed.  E.g. for a service deployed with three different versions, the value would be 3.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "max(kalix_service_revision{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}) by (kalix_region, kalix_service)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}}"
    }
   ]
  },
  {
   "title": "data ops",
   "type": "timeseries",
   "description": "Total number of reads from the DB by any component of the service(s) and endpoint(s)/method(s) selected.\n\nTotal number of writes by any component of a service(s) and endpoint(s)/method(s) selected.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum by (kalix_region, kalix_service, entity_name) (\n  irate(kalix_eventsourced_persisted_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]) or\n  irate(kalix_eventsourced_persisted_replicated_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]) or\n  irate(kalix_eventsourced_persisted_snapshots_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]) or\n  irate(kalix_valueentity_persisted_states_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]) or\n  irate(kalix_valueentity_persisted_replicated_states_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]) or\n  irate(kalix_workflowentity_persisted_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]) or\n  irate(kalix_workflowentity_persisted_replicated_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]) or\n  irate(kalix_workflowentity_persisted_snapshots_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]) or\n  label_replace(irate(kalix_view_upsert_rows_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]), \"entity_name\", \"$1\", \"view_name\", \"(.*)\")\n)\n",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - writes"
    },
    {
     "expr": "sum by (kalix_region, kalix_service, entity_name) (\n  irate(kalix_eventsourced_loaded_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]) or\n  irate(kalix_eventsourced_loaded_snapshots_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]) or\n  irate(kalix_valueentity_loaded_state_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]) or\n  irate(kalix_workflowentity_loaded_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]) or\n  irate(kalix_workflowentity_loaded_snapshots_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]) or\n  label_replace(irate(kalix_view_load_rows_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval]), \"entity_name\", \"$1\", \"view_name\", \"(.*)\")\n)\n",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - reads"
    }
   ]
  },
  { "title": "Agents", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 25 } },
  {
   "title": "agent commands received",
   "type": "timeseries",
   "description": "Rate of commands received per second over time.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "cmd/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "agent commands completed",
   "type": "timeseries",
   "description": "Rate of commands completed per second over time.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "cmd/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_completed_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "agent commands failed",
   "type": "timeseries",
   "description": "Rate of commands failed per second over time.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "cmd/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_failed_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "agent processing time (50th percentile)",
   "type": "timeseries",
   "description": "Agent commands processing time 50th percentile",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(kalix_agent_command_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kalix_agent_command_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "agent processing time (95 percentile)",
   "type": "timeseries",
   "description": "Agent commands processing time 95th percentile",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(kalix_agent_command_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kalix_agent_command_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "agent processing time (99th percentile)",
   "type": "timeseries",
   "description": "Agent commands processing time 99th percentile",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_agent_command_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kalix_agent_command_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "model calls",
   "type": "timeseries",
   "description": "Rate of requests received per second over time.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_model_received_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "model calls completed",
   "type": "timeseries",
   "description": "Rate of requests completed per second over time.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_model_completed_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "model calls failed",
   "type": "timeseries",
   "description": "Rate of requests failed per second over time.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_model_failed_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "model token usage",
   "type": "timeseries",
   "description": "Total token usage over time.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "tokens" } },
   "targets": [
    {
     "expr": "sum(increase(kalix_agent_model_token_input_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "input - {{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "sum(increase(kalix_agent_model_token_output_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "output - {{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "model processing time (50th percentile)",
   "type": "timeseries",
   "description": "Model calls processing time 50th percentile.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(kalix_agent_model_request_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kalix_agent_model_request_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "model processing time 95th percentile",
   "type": "timeseries",
   "description": "Model calls processing time 95th percentile.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(kalix_agent_model_request_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kalix_agent_model_request_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "model processing time (99th percentile)",
   "type": "timeseries",
   "description": "Model calls processing time 99th percentile.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_agent_model_request_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kalix_agent_model_request_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "tool calls",
   "type": "timeseries",
   "description": "Rate of received calls per second over time.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_tool_received_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "tool calls completed",
   "type": "timeseries",
   "description": "Rate of completed calls per second over time.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_tool_completed_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "tool calls failed",
   "type": "timeseries",
   "description": "Rate of failed calls per second over time.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_tool_failed_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "tool processing time (50th percentile)",
   "type": "timeseries",
   "description": "Tool calls processing time 50th percentile.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(kalix_agent_tool_request_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kalix_agent_tool_request_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "tool processing time (95th percentile)",
   "type": "timeseries",
   "description": "Tool calls processing time 95th percentile.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(kalix_agent_tool_request_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kalix_agent_tool_request_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "tool processing time (99th percentile)",
   "type": "timeseries",
   "description": "Tool calls processing time 99th percentile.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_agent_tool_request_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kalix_agent_tool_request_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "guardrail evaluations completed",
   "type": "timeseries",
   "description": "Rate of completed guardrail evaluations per second over time.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_guardrail_completed_evaluations_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "guardrail evaluations failed",
   "type": "timeseries",
   "description": "Rate of failed guardrail evaluations per second over time.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_guardrail_failed_evaluations_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "guardrails processing time (50th percentile)",
   "type": "timeseries",
   "description": "Guardrails evaluations processing time 50th percentile.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(kalix_agent_guardrail_evaluation_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kalix_agent_guardrail_evaluation_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "guardrails processing time (95th percentile)",
   "type": "timeseries",
   "description": "Guardrails evaluations processing time 95th percentile.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(kalix_agent_guardrail_evaluation_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kalix_agent_guardrail_evaluation_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "guardrails processing time (99th percentile)",
   "type": "timeseries",
   "description": "Guardrails evaluations processing time 99th percentile.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_agent_guardrail_evaluation_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kalix_agent_guardrail_evaluation_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "evaluations completed",
   "type": "timeseries",
   "description": "Rate of completed evaluations per second over time.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_evaluations_completed_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "evaluations failed",
   "type": "timeseries",
   "description": "Rate of failed evaluations per second over time.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_evaluations_failed_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  { "title": "Event Sourced Entities", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 97 } },
  {
   "title": "commands received",
   "type": "timeseries",
   "description": "Rate of commands received per second over time.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "cmd/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_eventsourced_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "stored events",
   "type": "timeseries",
   "description": "Rate of events stored per second, over time.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "(sum(irate(kalix_eventsourced_persisted_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) or vector(0)) + (sum(irate(kalix_eventsourced_persisted_replicated_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval])) or vector(0))",
     "legendFormat": "stored"
    }
   ]
  },
  {
   "title": "data ops (reads/writes)",
   "type": "timeseries",
   "description": "Total number of reads when loading from the DB the latest snapshot and the events afterward. \n\nTotal number of writes when persisting the events or the snapshots generated by the entity.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_eventsourced_loaded_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_eventsourced_loaded_snapshots_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"})\n)\n+\n(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_eventsourced_loaded_snapshots_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_eventsourced_loaded_events_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"})\n)\n",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - reads"
    },
    {
     "expr": "(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_eventsourced_persisted_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_eventsourced_persisted_replicated_events_total|kalix_eventsourced_persisted_snapshots_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"})\n)\n+\n(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_eventsourced_persisted_replicated_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_eventsourced_persisted_events_total|kalix_eventsourced_persisted_snapshots_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"})\n)\n+\n(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_eventsourced_persisted_snapshots_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_eventsourced_persisted_events_total|kalix_eventsourced_persisted_replicated_events_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"})\n)\n",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - writes"
    }
   ]
  },
  {
   "title": "processing time percentiles",
   "type": "timeseries",
   "description": "50th, 95th, and 99th percentiles for the processing time of the commands.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_eventsourced_command_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kalix_eventsourced_command_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(kalix_eventsourced_command_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p95"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kalix_eventsourced_command_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(kalix_eventsourced_command_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p50"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kalix_eventsourced_command_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p50"
    }
   ]
  },
  { "title": "Key Value Entities", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 113 } },
  {
   "title": "commands received",
   "type": "timeseries",
   "description": "Rate of commands received per second over time.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_valueentity_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "data ops (reads/writes)",
   "type": "timeseries",
   "description": "Total number of reads when loading its state from the DB. \n\nTotal number of writes when persisting its state in the DB.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_valueentity_loaded_state_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - reads"
    },
    {
     "expr": "sum(irate(kalix_valueentity_persisted_states_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - writes"
    }
   ]
  },
  {
   "title": "processing time percentiles",
   "type": "timeseries",
   "description": "50th, 95th, and 99th percentiles for the processing time of the commands.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_valueentity_command_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kalix_valueentity_command_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(kalix_valueentity_command_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p95"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kalix_valueentity_command_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(kalix_valueentity_command_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p50"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kalix_valueentity_command_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p50"
    }
   ]
  },
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 129 } },
  {
   "title": "messages received",
   "type": "timeseries",
   "description": "Number of messages per second over time.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_action_received_messages_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval])) by (kalix_region, kalix_service, action_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{action_name}}"
    }
   ]
  },
  {
   "title": "processing time percentiles",
   "type": "timeseries",
   "description": "Quantiles (50, 95 and 99) for the processing time of the commands.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_action_message_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{action_name}} - p99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kalix_action_message_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{action_name}} - p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(kalix_action_message_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{action_name}} - p95"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kalix_action_message_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{action_name}} - p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(kalix_action_message_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{action_name}} - p50"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kalix_action_message_processing_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{action_name}} - p50"
    }
   ]
  },
  { "title": "Views", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 137 } },
  {
   "title": "rows updated",
   "type": "timeseries",
   "description": "Number of rows updated per second over time.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_view_upsert_rows_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\",view_name=~\"$view\"}[$__rate_interval])) by (kalix_region, kalix_service, view_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{view_name}}"
    }
   ]
  },
  {
   "title": "query request received",
   "type": "timeseries",
   "description": "Number of query requests received per second over time.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_view_query_received_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\",view_name=~\"$view\"}[$__rate_interval])) by (kalix_region, kalix_service, view_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{view_name}}"
    }
   ]
  },
  {
   "title": "average update size",
   "type": "timeseries",
   "description": "Average size of each update. Calculated by dividing the total size of the update by the number of rows.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_view_query_received_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\",view_name=~\"$view\"}[$__rate_interval])) by (kalix_region, kalix_service, view_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{view_name}}"
    }
   ]
  },
  {
   "title": "average query result size",
   "type": "timeseries",
   "description": "The average size of a query. Calculated by dividing the total size of the queries by the number of queries requested.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_view_query_result_bytes_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\",view_name=~\"$view\"}[$__rate_interval])) by (kalix_region, kalix_service, view_name)\n      /\n      sum(irate(kalix_view_query_received_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\",view_name=~\"$view\"}[$__rate_interval])) by (kalix_region, kalix_service, view_name)\n      ",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{view_name}}"
    }
   ]
  },
  { "title": "Workflows", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 153 } },
  {
   "title": "commands received",
   "type": "timeseries",
   "description": "Rate of commands received per second over time.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_workflowentity_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "commands completed",
   "type": "timeseries",
   "description": "Rate of commands completed per second over time.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_workflowentity_completed_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "commands failed",
   "type": "timeseries",
   "description": "Rate of commands failed per second over time.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_workflowentity_failed_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "command processing time percentiles",
   "type": "timeseries",
   "description": "Quantiles (50, 95 and 99) for the processing time of the commands.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_workflowentity_command_total_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kalix_workflowentity_command_total_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(kalix_workflowentity_command_total_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p95"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kalix_workflowentity_command_total_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(kalix_workflowentity_command_total_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p50"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kalix_workflowentity_command_total_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p50"
    }
   ]
  },
  {
   "title": "steps started",
   "type": "timeseries",
   "description": "Rate of steps started per second over time.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_workflowentity_started_steps_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "steps completed",
   "type": "timeseries",
   "description": "Rate of steps completed per second over time.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_workflowentity_completed_steps_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "steps failed",
   "type": "timeseries",
   "description": "Rate of steps failed per second over time.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_workflowentity_failed_steps_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "step processing time percentiles",
   "type": "timeseries",
   "description": "Quantiles (50, 95 and 99) for the processing time of the steps.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_workflowentity_step_total_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kalix_workflowentity_step_total_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(kalix_workflowentity_step_total_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p95"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kalix_workflowentity_step_total_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(kalix_workflowentity_step_total_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p50"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kalix_workflowentity_step_total_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p50"
    }
   ]
  },
  {
   "title": "data ops (reads/writes)",
   "type": "timeseries",
   "description": "Total number of reads when loading from the DB the latest snapshot and the events afterward.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_workflowentity_loaded_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_workflowentity_loaded_snapshots_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"})\n)\n+\n(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_workflowentity_loaded_snapshots_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_workflowentity_loaded_events_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"})\n)\n",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - reads"
    },
    {
     "expr": "(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_workflowentity_persisted_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_workflowentity_persisted_replicated_events_total|kalix_workflowentity_persisted_snapshots_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"})\n)\n+\n(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_workflowentity_persisted_replicated_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_workflowentity_persisted_events_total|kalix_workflowentity_persisted_snapshots_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"})\n)\n+\n(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_workflowentity_persisted_snapshots_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_workflowentity_persisted_events_total|kalix_workflowentity_persisted_replicated_events_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"})\n)\n",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - writes"
    }
   ]
  },
  { "title": "Consumers", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 177 } },
  {
   "title": "projection instances",
   "type": "timeseries",
   "description": "Number of projection instances currently running for Consumers and Views.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamp_min(\n  (\n    sum(kalix_projection_started_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}) by (kalix_region, kalix_service, projection_name)\n    -\n    sum(kalix_projection_stopped_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}) by (kalix_region, kalix_service, projection_name)\n  )\n  or\n  (\n    sum(kalix_projection_started_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}) by (kalix_region, kalix_service, projection_name)\n  ),\n  0\n)\n",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "events consumed",
   "type": "timeseries",
   "description": "The processing rate of events consumed by a Consumer or a View.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_projection_completed_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "subscriptions failed",
   "type": "timeseries",
   "description": "Failures consuming events from a Consumer or a View.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_projection_failed_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "events backlog lag",
   "type": "timeseries",
   "description": "The lag (timestamp difference) between the most recently produced event and the most recently consumed event, for a Consumer or View.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kalix_projection_backlog_lag_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}} - {{projection_key}}"
    }
   ]
  },
  {
   "title": "events consumption lag - max",
   "type": "timeseries",
   "description": "Max delay in consumption of events by a Consumer or a View.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (kalix_service, projection_name) (sum(irate(kalix_projection_consumer_lag_seconds_sum{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name, projection_key) / sum(irate(kalix_projection_consumer_lag_seconds_count{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name, projection_key))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "events consumption lag - p50",
   "type": "timeseries",
   "description": "50th percentile on the delay in consumption of events by a Consumer or a View.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(kalix_projection_consumer_lag_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(kalix_projection_consumer_lag_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "events consumption lag - p95",
   "type": "timeseries",
   "description": "95th percentile on the delay in consumption of events by a Consumer or a View.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(kalix_projection_consumer_lag_seconds_bucket{ kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kalix_projection_consumer_lag_seconds{ kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "events consumption lag - p99",
   "type": "timeseries",
   "description": "99th percentile on the delay in consumption of events by a Consumer or a View.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_projection_consumer_lag_seconds_bucket{ kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kalix_projection_consumer_lag_seconds{ kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "events processing time - average",
   "type": "timeseries",
   "description": "Average duration for event processing (including user service and persist) by a Consumer or a View.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_projection_processing_time_seconds_sum[$__rate_interval])) by (kalix_region, kalix_service, projection_name) / sum(irate(kalix_projection_processing_time_seconds_count[$__rate_interval])) by (kalix_region, kalix_service, projection_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "events processing time - p50",
   "type": "timeseries",
   "description": "50th percentile duration for event processing (including user service and persist) by a Consumer or a View.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(kalix_projection_processing_time_seconds_bucket{ kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(kalix_projection_processing_time_seconds{ kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "events processing time - p95",
   "type": "timeseries",
   "description": "95th percentile duration for event processing (including user service and persist) by a Consumer or a View.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(kalix_projection_processing_time_seconds_bucket{ kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kalix_projection_processing_time_seconds{ kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "events processing time - p99",
   "type": "timeseries",
   "description": "99th percentile duration for event processing (including user service and persist) by a Consumer or a View.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_projection_processing_time_seconds_bucket{ kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kalix_projection_processing_time_seconds{ kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 201 } },
  {
   "title": "replicated events",
   "type": "timeseries",
   "description": "The rate of multi-region event replication.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_projection_completed_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$replication_projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "replication lag - average",
   "type": "timeseries",
   "description": "Average lag for multi-region event replication.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_projection_consumer_lag_seconds_sum{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$replication_projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name)\n      /\n      sum(irate(kalix_projection_consumer_lag_seconds_count{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$replication_projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name)\n      ",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "replication failures",
   "type": "timeseries",
   "description": "Failure rate for multi-region replication.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_projection_failed_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$replication_projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "switch primary time percentiles",
   "type": "timeseries",
   "description": "50th, 95th, and 99th percentiles for the switch primary time.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(kalix_eventsourced_switch_primary_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le)) OR histogram_quantile(0.99, sum(irate(kalix_valueentity_switch_primary_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kalix_eventsourced_switch_primary_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)) OR histogram_quantile(0.99, sum(rate(kalix_valueentity_switch_primary_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(kalix_eventsourced_switch_primary_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le)) OR histogram_quantile(0.95, sum(irate(kalix_valueentity_switch_primary_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p95"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kalix_eventsourced_switch_primary_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)) OR histogram_quantile(0.95, sum(rate(kalix_valueentity_switch_primary_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(kalix_eventsourced_switch_primary_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le)) OR histogram_quantile(0.50, sum(irate(kalix_valueentity_switch_primary_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name, le))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p50"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kalix_eventsourced_switch_primary_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)) OR histogram_quantile(0.50, sum(rate(kalix_valueentity_switch_primary_time_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name))",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - p50"
    }
   ]
  },
  {
   "title": "switch primary count",
   "type": "timeseries",
   "description": "Rate of switching primary operations per second over time.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_eventsourced_switch_primary_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name) OR sum(irate(kalix_valueentity_switch_primary_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "switch primary failures",
   "type": "timeseries",
   "description": "Failure rate for switch primary operations.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_eventsourced_switch_primary_failed_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name) OR sum(irate(kalix_valueentity_switch_primary_failed_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "conflicts detected",
   "type": "timeseries",
   "description": "Rate of conflict detection in operations per second.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_eventsourced_conflicts_detected_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name) OR sum(irate(kalix_valueentity_conflicts_detected_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "conflicts resolved",
   "type": "timeseries",
   "description": "Rate of conflict resolution in operations per second.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_eventsourced_conflicts_resolved_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name) OR sum(irate(kalix_valueentity_conflicts_resolved_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  }
 ]
}