{
 "title": "Service overview",
 "tags": [ "kalix-managed" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kalix_region",
    "label": "Region",
    "query": "label_values(kalix_service_revision, kalix_region)"
   },
   {
    "name": "kalix_service",
    "label": "Service",
    "query": "label_values(kalix_service_revision{kalix_region=~\"$kalix_region\"}, kalix_service)"
   },
   {
    "name": "grpc_service",
    "label": "Component",
    "query": "label_values({__name__=~\"kalix_proxy_http_requests_total|kalix_proxy_grpc_requests_total\", kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"},grpc_service)"
   },
   {
    "name": "http_target",
    "label": "HTTP Target",
    "query": "label_values(kalix_proxy_http_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", grpc_service=~\"$grpc_service\"},http_target)"
   },
   {
    "name": "grpc_method",
    "label": "GRPC Method",
    "query": "label_values(kalix_proxy_grpc_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", grpc_service=~\"$grpc_service\"},grpc_method)"
   },
   {
    "name": "agent",
    "label": "Agent",
    "query": "label_values(kalix_agent_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"},agent_id)"
   },
   {
    "name": "event_sourced_entity",
    "label": "Event Sourced Entity",
    "query": "label_values(kalix_eventsourced_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"},entity_name)"
   },
   {
    "name": "key_value_entity",
    "label": "Key Value Entity",
    "query": "label_values(kalix_valueentity_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"},entity_name)"
   },
   {
    "name": "view",
    "label": "View",
    "query": "label_values(kalix_view_upsert_rows_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"},view_name)"
   },
   {
    "name": "workflow_entity",
    "label": "Workflow Entity",
    "query": "label_values(kalix_workflowentity_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\"}, entity_name)"
   },
   {
    "name": "projection",
    "label": "Consumers",
    "query": "label_values(kalix_projection_consumer_lag_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_type!=\"replicated_event_sourced_projection\"},projection_name)"
   },
   {
    "name": "replication_projection",
    "label": "Replication Projection",
    "query": "label_values(kalix_projection_consumer_lag_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_type=\"replicated_event_sourced_projection\"},projection_name)"
   }
  ]
 },
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 1 } },
  {
   "title": "successful requests",
   "type": "timeseries",
   "description": "Rate of successful requests per second (reqs/s) over time, by endpoint.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate({__name__=~\"kalix_proxy_grpc_requests_total\", kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", grpc_method=~\"$grpc_method\", grpc_status_code=\"0\"}[$__rate_interval])) by (kalix_region, kalix_service, grpc_method) OR sum(irate({__name__=~\"kalix_proxy_http_requests_total\", kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", http_target=~\"$http_target\", http_status_code=~\"(2|3)..\"}[$__rate_interval])) by (kalix_region, kalix_service, http_target)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{grpc_method}}{{http_target}}"
    }
   ]
  },
  {
   "title": "failed requests",
   "type": "timeseries",
   "description": "Rate of requests (reqs/s) that raised an error when processing the request, over time, by endpoint.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(irate({__name__=~\"kalix_proxy_grpc_requests_total\", kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", grpc_method=~\"$grpc_method\", grpc_status_code=~\"1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16\"}[$__rate_interval])) by (kalix_region, kalix_service, grpc_method) OR sum(irate({__name__=~\"kalix_proxy_http_requests_total\", kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", http_target=~\"$http_target\", http_status_code=~\"(4|5)..\"}[$__rate_interval])) by (kalix_region, kalix_service, http_target)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{grpc_method}}{{http_target}}"
    }
   ]
  },
  {
   "title": "processing time heapmap",
   "type": "heatmap",
   "description": "Number of calls that fall into each processing time bucket over time.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_proxy_grpc_request_duration_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\",grpc_method=~\"$grpc_method\"}[$__rate_interval])) by (le) OR sum(irate(kalix_proxy_http_request_duration_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\",http_target=~\"$http_target\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Agents", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "agent commands received",
   "type": "timeseries",
   "description": "Rate of commands received per second over time.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cmd/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  {
   "title": "processing time heatmap",
   "type": "heatmap",
   "description": "Number of agent calls that fall into each processing time bucket over time.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_agent_command_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "model token usage",
   "type": "timeseries",
   "description": "Total token usage over time.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "tokens" } },
   "targets": [
    {
     "expr": "sum(increase(kalix_agent_model_token_input_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "input - {{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    },
    {
     "expr": "sum(increase(kalix_agent_model_token_output_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", agent_id=~\"$agent\"}[$__rate_interval])) by (kalix_region, kalix_service, agent_id)",
     "legendFormat": "output - {{kalix_region}} - {{kalix_service}} - {{agent_id}}"
    }
   ]
  },
  { "title": "Event Sourced Entities", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 17 } },
  {
   "title": "commands received",
   "type": "timeseries",
   "description": "Rate of commands received per second over time.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cmd/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_eventsourced_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "processing time heatmap",
   "type": "heatmap",
   "description": "Number of Event Sourced Entity calls that fall into each processing time bucket over time.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_eventsourced_command_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "data ops (reads/writes)",
   "type": "timeseries",
   "description": "Total number of reads when loading from the DB the latest snapshot and the events afterward. \n\nTotal number of writes when persisting the events or the snapshots generated by the entity.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_eventsourced_loaded_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_eventsourced_loaded_snapshots_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"})\n)\n+\n(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_eventsourced_loaded_snapshots_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_eventsourced_loaded_events_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"})\n)\n",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - reads"
    },
    {
     "expr": "(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_eventsourced_persisted_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_eventsourced_persisted_replicated_events_total|kalix_eventsourced_persisted_snapshots_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"})\n)\n+\n(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_eventsourced_persisted_replicated_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_eventsourced_persisted_events_total|kalix_eventsourced_persisted_snapshots_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"})\n)\n+\n(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_eventsourced_persisted_snapshots_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_eventsourced_persisted_events_total|kalix_eventsourced_persisted_replicated_events_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$event_sourced_entity\"})\n)\n",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - writes"
    }
   ]
  },
  { "title": "Key Value Entities", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 25 } },
  {
   "title": "commands received",
   "type": "timeseries",
   "description": "Rate of commands received per second over time.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_valueentity_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "processing time heatmap",
   "type": "heatmap",
   "description": "Number of Key Value Entity calls that fall into each processing time bucket over time.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_valueentity_command_processing_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "data ops (reads/writes)",
   "type": "timeseries",
   "description": "Total number of reads when loading its state from the DB. \n\nTotal number of writes when persisting its state in the DB.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_valueentity_loaded_state_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - reads"
    },
    {
     "expr": "sum(irate(kalix_valueentity_persisted_states_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$key_value_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - writes"
    }
   ]
  },
  { "title": "Views", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 33 } },
  {
   "title": "rows updated",
   "type": "timeseries",
   "description": "Number of rows updated per second over time.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_view_upsert_rows_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\",view_name=~\"$view\"}[$__rate_interval])) by (kalix_region, kalix_service, view_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{view_name}}"
    }
   ]
  },
  {
   "title": "query request received",
   "type": "timeseries",
   "description": "Number of query requests received per second over time.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_view_query_received_requests_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\",view_name=~\"$view\"}[$__rate_interval])) by (kalix_region, kalix_service, view_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{view_name}}"
    }
   ]
  },
  { "title": "Workflows", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 41 } },
  {
   "title": "commands received",
   "type": "timeseries",
   "description": "Rate of commands received per second over time.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_workflowentity_received_commands_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (kalix_region, kalix_service, entity_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}}"
    }
   ]
  },
  {
   "title": "processing time heatmap",
   "type": "heatmap",
   "description": "Number of Workflow calls that fall into each processing time bucket over time.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_workflowentity_command_total_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "data ops (reads/writes)",
   "type": "timeseries",
   "description": "Total number of reads when loading from the DB the latest snapshot and the events afterward.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_workflowentity_loaded_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_workflowentity_loaded_snapshots_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"})\n)\n+\n(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_workflowentity_loaded_snapshots_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_workflowentity_loaded_events_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"})\n)\n",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - reads"
    },
    {
     "expr": "(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_workflowentity_persisted_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_workflowentity_persisted_replicated_events_total|kalix_workflowentity_persisted_snapshots_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"})\n)\n+\n(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_workflowentity_persisted_replicated_events_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_workflowentity_persisted_events_total|kalix_workflowentity_persisted_snapshots_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"})\n)\n+\n(\n  sum by (kalix_region, kalix_service, entity_name) (irate(kalix_workflowentity_persisted_snapshots_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval]))\nor\n  0 * sum by (kalix_region, kalix_service, entity_name) ({__name__=~\"kalix_workflowentity_persisted_events_total|kalix_workflowentity_persisted_replicated_events_total\",kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"})\n)\n",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{entity_name}} - writes"
    }
   ]
  },
  { "title": "Consumers", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 49 } },
  {
   "title": "events consumed",
   "type": "timeseries",
   "description": "The processing rate of events consumed by a Consumer or a View.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_projection_completed_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "processing time heatmap",
   "type": "heatmap",
   "description": "Number of messages processed that fall into each processing time bucket over time.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_workflowentity_command_total_time_seconds_bucket{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", entity_name=~\"$workflow_entity\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "subscriptions failed",
   "type": "timeseries",
   "description": "Failures consuming events from a Consumer or a View.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "op/s" } },
   "targets": [
    {
     "expr": "sum(irate(kalix_projection_failed_total{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}[$__rate_interval])) by (kalix_region, kalix_service, projection_name)",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}}"
    }
   ]
  },
  {
   "title": "events backlog lag",
   "type": "timeseries",
   "description": "The lag (timestamp difference) between the most recently produced event and the most recently consumed event, for a Consumer or View.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kalix_projection_backlog_lag_seconds{kalix_region=~\"$kalix_region|\", kalix_service=~\"$kalix_service\", projection_name=~\"$projection\"}",
     "legendFormat": "{{kalix_region}} - {{kalix_service}} - {{projection_name}} - {{projection_key}}"
    }
   ]
  }
 ]
}